### PR TITLE
initial build of mpl-probscale 0.2.3

### PR DESCRIPTION
**Pull request by phobson**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I think if you create a gh-pages branch in github.com/matplotlib/mpl-probscale it will be served as 
matplotlib.org/mpl-probscale that might be simpler? That is how we do the devdocs at matplotlib.org/devdocs

**Comment by tacaswell** [comment]
There is a balance on the size of the built docs.  We host the cmocean docs directly in this repo to prevent bloating the main cmocean repo.

**Comment by jenshnielsen** [comment]
Yes that makes sense but as far as I can see mpl-probscale is not currently hosted in the matplotlib organisation? Perhaps it should be?

**Comment by phobson** [comment]
@jenshnielsen I'm actively moving mpl-probscale to the MPL org. 

I was having permission issues when trying to create the matplotlib/mpl-probscale repo.

@tacaswell has sorted those out for me and I'll resume that work tonight.

**Comment by jenshnielsen** [comment]
Ok in that case @tacaswell is probably right, never mind my suggestions

**Comment by phobson** [comment]
alright, hold on to yer butts 🦎

**Pull request merged**
