### PR TITLE
Redirect to stable, add sitemap.xml

### LINKED ISSUE #35: root pages should redirect to versioned pages
`matplotlib.org` should redirect to `matplotlib.org/latest/`, which should redirect to `matplotlib.org/3.0.2/` or whatever "latest" is.  Then people making links can link the versions link and it won't die if we rearrange doc pages (and it will clearly say what the link is).

The proper way to do this would be with an .htaccess file, but GitHub pages doesn't support that.  

So far, looks like we can't do this with soft links.

We could do with http-equiv redirect.  But that has to be in the header of each file which kind of means having two versions of the docs lying around doing the same thing, but with one version pointing to the canonical version.   https://www.w3.org/TR/WCAG20-TECHS/H76.html

Another option is to migrate to readthedocs https://readthedocs.org

### PR DESCRIPTION
**Pull request by jklymak**
Close #35  

Pretty hard to review, but all that has happened is:

This is a suggested change of the site org.  

### soft link `stable` to `3.3.3`

This would of course need to be updated on a new release

```
lrwxr-xr-x 1 jklymak staff 5 Jan 17 17:41 stable -> 3.3.3
```

### softlink all of `root` to `stable`

Everything that is in root that had a counterpart in `3.3.3` (which now is the same as `stable`) is softlinked to `stable`.  This keeps all our old links exactly the same.  Note that `matplotlib.org/index.html` will *not* resolve to `matplotlib.org/stable/index.html`  However, we can tell google etc to look in `stable`.  We can also set the canonical url to be `matplotlib.org/stable`.  

```
lrwxr-xr-x    1 jklymak staff   21 Jan 17 18:56 searchindex.js -> stable/searchindex.js
lrwxr-xr-x    1 jklymak staff   18 Jan 17 18:56 search.html -> stable/search.html
lrwxr-xr-x    1 jklymak staff   23 Jan 17 18:56 py-modindex.html -> stable/py-modindex.html
lrwxr-xr-x    1 jklymak staff   18 Jan 17 18:56 objects.inv -> stable/objects.inv
lrwxr-xr-x    1 jklymak staff   17 Jan 17 18:56 index.html -> stable/index.html
lrwxr-xr-x    1 jklymak staff   20 Jan 17 18:56 genindex.html -> stable/genindex.html
lrwxr-xr-x    1 jklymak staff   20 Jan 17 18:56 contents.html -> stable/contents.html
lrwxr-xr-x    1 jklymak staff   18 Jan 17 18:56 citing.html -> stable/citing.html
lrwxr-xr-x    1 jklymak staff   21 Jan 17 18:56 Matplotlib.pdf -> stable/Matplotlib.pdf
lrwxr-xr-x    1 jklymak staff   12 Jan 17 18:56 users -> stable/users
lrwxr-xr-x    1 jklymak staff   16 Jan 17 18:56 tutorials -> stable/tutorials
lrwxr-xr-x    1 jklymak staff   25 Jan 17 18:56 thirdpartypackages -> stable/thirdpartypackages
lrwxr-xr-x    1 jklymak staff   16 Jan 17 18:56 resources -> stable/resources
lrwxr-xr-x    1 jklymak staff   15 Jan 17 18:55 glossary -> stable/glossary
lrwxr-xr-x    1 jklymak staff   14 Jan 17 18:55 gallery -> stable/gallery
lrwxr-xr-x    1 jklymak staff   10 Jan 17 18:55 faq -> stable/faq
lrwxr-xr-x    1 jklymak staff   12 Jan 17 18:55 devel -> stable/devel
lrwxr-xr-x    1 jklymak staff   10 Jan 17 18:55 api -> stable/api
lrwxr-xr-x    1 jklymak staff   14 Jan 17 18:55 _static -> stable/_static
lrwxr-xr-x    1 jklymak staff   15 Jan 17 18:55 _sources -> stable/_sources
lrwxr-xr-x    1 jklymak staff   15 Jan 17 18:55 _modules -> stable/_modules
lrwxr-xr-x    1 jklymak staff   14 Jan 17 18:55 _images -> stable/_images
lrwxr-xr-x    1 jklymak staff   17 Jan 17 18:55 _downloads -> stable/_downloads
```

### `sitemap.xml`

This should weight the old docs lower than the new docs.

### CODE REVIEW

**Comment by jklymak** [comment]
An example of this working: https://jklymak.github.io/matplotlib.github.com/stable/index.html

**Comment by jklymak** [comment]
ping @dstansby as well as @QuLogic and @tacaswell, as I think he has some experience and comments about organizing the webpage.

**Comment by QuLogic** [comment]
How do we update this?

**Comment by jklymak** [comment]
I think the changes in the second commit of https://github.com/matplotlib/matplotlib/pull/19319 take care of that...

Basically:
- build into `3.3.4` (as before)
- link `stable` to `3.3.4/` (don't do the rsync step)
- edit `sitemap.xml`

**Comment by QuLogic** [comment]
Does this not replace everything at the top-level, thus deleting all the old versions of files without redirect? And will continue to do that for every release that deleted files?

**Comment by jklymak** [comment]
Nothing is "redirected".  Its just soft linked.   Everything that used to be top level and is also in 3.3.3 is soft linked to `stable`.  `stable` is soft linked to `3.3.3/`.  When you do a release and change the softlink `stable` to `3.3.4` it should just redirect there instead of `3.3.3` and all the old top-level links will now point to `3.3.4`

So consider `resources`.  This PR removed the top-level `resources` and replaced it by a soft link to `resources->stable/resources`.  You can now point `stable` wherever you want and so long as it has ` resources` subdirectory `matplotlib.org/resources` will resolve to it.

**Comment by jklymak** [comment]
Oh, I think I misunderstood you.  Do you mean if `/3.3.3/boo/foo.html` exists, but is removed in `/3.3.4/boo`, it should stay at `/boo/foo.html`?  Now that I look at what we do, I guess that is indeed what we do.  

I'd argue that is a mistake though - why would we keep files around that are only in old versions?

**Comment by QuLogic** [comment]
It's not that we _want_ to do this; it's just that it would break many old links, and @tacaswell would rather we put in redirects there. We haven't done this though, because there are tons of leftovers at this point.

**Comment by jklymak** [comment]
Well put me firmly in the camp of "no link is better than an obsolete link".  We can add a nice 404 message that explains how to search the old versions. 

However as a stopgap we could just add the Sitamap.XMl and add a robots.txt that tells search engines to stop crawling the top level.

**Comment by jklymak** [comment]
A less destructive version is at #48.

**Comment by jklymak** [comment]
I'll close in favour of #49, which conserves all old files as well...

**Pull request closed without merging**
