### PR TITLE
TST: temporary test to be removed

### PR DESCRIPTION
**Pull request by jklymak**
This is a test, and if merged should be reverted...

### CODE REVIEW

**Comment by jklymak** [comment]
ping @tacaswell if we merge this, then we can see what matplotlib.org/_junk.html renders as...

**Comment by jklymak** [comment]
cross ref #29

**Comment by jklymak** [comment]
Oops guess I did that incorrectly.

**Comment by tacaswell** [comment]
https://matplotlib.org/_junk.html/ shows a version of the home page without a re-direct (and oddly without css?).

**Comment by jklymak** [comment]
Drat.  Well it was worth a try; the lack of redirects on GitHub pages is a pretty big hangup.

**Pull request merged**
