### PR TITLE
ENH: softlink current docs

### PR DESCRIPTION
**Pull request by jklymak**
This (big-looking) PR actually just does one simple thing:

```
ln -s 3.0.2 latest
rm -rf gallery # etc....
ln -s latest/gallery gallery  # etc
```

So basically all calls to `matplotlib.org/index.html` show up as `matplotlib.org/3.0.2/index.html`.  If we want to link latest, you can always link `matplotlib.org/latest/index.html`;  Someone who deploys the docs will need to update the softlink of course when a new version is released.

### CODE REVIEW

**Comment by tacaswell** [comment]
This won't solve the problem we currently have when new version of the docs add or remove files, it just uses symlinks instead of copying.

**Comment by jklymak** [comment]
The link will be to `matplotlib.org/3.0.2/file_that_gets_moved_in_3.1.html`  so the version is in the name and at the top of the page....

**Comment by jklymak** [comment]
Its *possible* to get to 
`matplotlib.org/file_that_gets_moved_in_3.1.html`, so I guess thats a drawback.  But you'd have to manually go there.

**Comment by tacaswell** [comment]
It is not clear to me that the url is actually going to change/auto-forward.  From the servers point of view `file.html` still exists, that it gets that by following a symlink should be opaque to it....

**Comment by jklymak** [comment]
Fair enough - afraid I don't have a static github pages page (mine renders in jekyl).  Would it be a problem to push a test subdir?

**Comment by jklymak** [comment]
OK Closing because this method of redirects doesn't work.  Its pretty tough to do anything flexibly from a static GitHub page...

**Pull request closed without merging**
