### PR TITLE
Hide old docs from search engines via canonical link

### PR DESCRIPTION
**Pull request by JazzTap**
Project initiated with @jlegs to point search engines (and users, gently) at current docs. Dumb approach used: delete version string from url (and put absolute link to matplotlib.org to avoid baseurl shenanigans).

All HTML parsed through lxml by 'tools/docs_deprecator' notebook or script. Only change expected besides whitespace, and property ordering, is 1) a \<link\> at the bottom of \<head\> and 2) a \<div\> at the top of \<body\>. (The bot-forwarder and human-forwarder respectively.)

Corresponding comment in issue tracker: https://github.com/matplotlib/matplotlib/issues/10016#issuecomment-405035140

Note that in an ideal world we'd forward pages using a database of pages & their descendants, replacements, whatever. Their automatic computation is compute-heavy, as discussed above.

### CODE REVIEW

**Comment by QuLogic** [comment]
There are a _ton_ of extraneous changes here; is there a way to get it to only do the two things you mentioned? It's not just whitespace changes that are added.

**Comment by JazzTap** [comment]
That's lxml snapping all the docs to its grammar. But I didn't spot anything else beyond property re-ordering. Are there semantic changes?

As I understand it, all html is (was) machine-generated from source in the first place. But instead of parsing, one could regex carefully for the lines of form `</head> <body>` as the point of insertion.

**Comment by tacaswell** [comment]
There appears to be a way to get git to not add whitespace only changes (https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes).

We should hold of on worry about the whitespace for now, @JazzTap and I are at the scipy sprints and agreed in person to focus on using the `cleanup.py` script to also add these changes to the files at the top level of the domain first.

**Comment by Carreau** [comment]
See #39 that only change a single line per file.

**Comment by jklymak** [comment]
I'll close this in lieu of #49 which does the same thing almost.  Thanks a lot for the work on this though - it was very helpful.

**Pull request closed without merging**
