### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by szemek**
Tiny fix: antialised => antialiased :)

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks for the contribution.  I don't mean to discourage contribution, but these docs are generated from the source sphinx docs that live in the matplotlib/matplotlib repository, and we shouldn't be directly updating the generated files.  Please make a PR over at matplotlib/matplotlib on the rst files and/or docstrings that generated these files.

**Comment by szemek** [comment]
Thanks. What do you think about README file with information about this repository: a purpose, in what cases is possible to contribute to it?

**Comment by jenshnielsen** [comment]
A readme documenting that this is the Docs repo and that it is generated (mostly) from the main repo makes sense to me

**Comment by mdboom** [comment]
Great idea about the README.

**Pull request closed without merging**
