### PR TITLE
Change Downloads page to refer to PyPI, not SF

### PR DESCRIPTION
**Pull request by mdboom**
Fix matplotlib/matplotlib#5227

### CODE REVIEW

**Comment by pelson** [comment]
Ironically the PyPI entry still points at sourceforge (I'm not an index owner, otherwise I'd have fixed it).
There is a whole archive of previous downloads on SourceForge which *may* be of value to somebody, I don't propose we maintain all of those links, but is it worth us linking to the SourceForge archive for older downloads?

**Comment by mdboom** [comment]
Good point.  I'll add a link along the lines of "for older downloads see SourceForge".  Updating the link from PyPI to Sourceforge.

I'll update "Download URL" on PyPI to point to `http://matplotlib.org/users/installing.html`, which is what we plan to do for new releases going forward.

**Comment by mdboom** [comment]
I've updated the PyPI download links back to 1.3.0.  (It's a manual process).  Also added a note about where to find historical releases on SourceForge.

I'm going to merge this and create a new issue for the better page layout using the PyPI API -- that's a non-trivial project and the listing that PyPI provides is good enough for now.  It also occurs to me that trying to submit a patch to PyPI to sort by platform may be even better than just fixing the problem for matplotlib.

**Comment by tacaswell** [comment]
I have a vague sense that there was/is a major pypi re-design going on?

**Comment by mdboom** [comment]
@tacaswell: I wasn't aware of the redesign, but it seems you're right:

https://github.com/pypa/warehouse/issues/717

I'm going to sign up for usability testing and see if I can influence anything that might help matplotlib.  (We always seem to push boundaries of tools...)

**Comment by efiring** [comment]
On 2015/10/13 4:30 AM, Michael Droettboom wrote:
> I'm going to merge this and create a new issue for the better page
> layout using the PyPI API -- that's a non-trivial project and the
> listing that PyPI provides is good enough for now. It also occurs to me
> that trying to submit a patch to PyPI to sort by platform may be even
> better than just fixing the problem for matplotlib.

Yes, leave it to the PyPI level, by all means.  Or just ignore it.  This 
is very low priority for mpl.

**Pull request merged**
