### PR TITLE
Add rel=canonical to most old html files.

### PR DESCRIPTION
**Pull request by Carreau**
rel=canonical  is supposed to be helpful for search engine to know
which pages a search engine should promote.

This is _not_ a redirect.

If a file exists and is not in a versioned (x.y.z) folder; consider it
as a potential "canonical" target

If a file exist in a versioned doc of matplotlib make its rel=canonical
point to the corresponding candidate.

Example:

    path/to/foo.html -> candidate as being canonical
    3.0.1/path/to/foo.html > set rel=canonical to matplotlib.org/path/to/foo.html

Special case the `examples` and `gallery` folder.
The `examples` folder is from old matplotlib version (2.0.2) but still
quite popular on Google; special case.

1) Apply the same rule as above but from withing `examples` toward
`gallery`:

    /gallery/path/to/foo.html -> candidate as being canonical
    /example/path/to/foo.html > set rel=canonical to matplotlib.org/gallery/path/to/foo.html

    This took care of 145 files.

2) Many examples were "moved" during examples -> gallery transition. If
filename is unique in gallery; use this as a potential heuristic for
detecting move:

    /gallery/path/to/verryuniquename.html -> candidate as being canonical as the filename is unique !
    /example/old/location/verryuniquename.html > set rel=canonical to matplotlib.org/gallery/path/to/verryuniquename.html

    This took care of 185 files in example
    Leaving 271 "orphan"

3) Resolve chain of rel-canonical. Fix links that point to example
that themselves point to gallery.

    /gallery/path/to/verryuniquename.html
    /example/old/location/verryuniquename.html ->  matplotlib.org/gallery/path/to/verryuniquename.html
    /2.0.2/example/old/location/verryuniquename.html -> should point to /example/....
                                                       make it point to /gallery/....

No files with existing rel=canonical have been touched. This will
likely only affect pre-3.0 documentation files.

---- 

Obviously scripted, but kind of ugly: 

https://gist.github.com/Carreau/d2b3e36b65d4155827539ef462860444

I paid attension to avoid doing any other changes than adding a single line to target files; so can try to do changes.

### CODE REVIEW

**Comment by Carreau** [comment]
Need to look at the `users/` doc as well likely.

**Comment by ImportanceOfBeingErnest** [comment]
For `users/` it might be more complicated, because partially it contains files from the actual docs, e.g.

https://matplotlib.org/users/navigation_toolbar.html  
https://matplotlib.org/users/event_handling.html


and partially it contains files where the current version is actually in the tutorials or some other section, e.g.

https://matplotlib.org/users/annotations.html

should now really be 

https://matplotlib.org/tutorials/text/annotations.html

**Comment by ImportanceOfBeingErnest** [comment]
Is this ready to go? Shall we just merge this and see what happens? 

Do you have some example search terms to be able to later verify if it had the desired effect?

**Comment by Carreau** [comment]
> Is this ready to go?

I believe it is. 

> Shall we just merge this and see what happens?

That would be great. 

> Do you have some example search terms to be able to later verify if it had the desired effect?

We can either look at the traffic on google analytics (though I don't have access). 

My use case was the following search in google, `matplotlib gallery`, in incognito mode:
 1.  `https://matplotlib.org/gallery.html` 
 2. `https://matplotlib.org/3.1.0/gallery/index.html`
 3. `https://matplotlib.org/2.1.1/gallery/index.html`
 

Matplotlib examples also: 

  1. `https://matplotlib.org/examples/`
  2. `https://matplotlib.org/3.1.1/gallery/index.html`

**Comment by Carreau** [comment]
Note that there are more fixes that should come on top of these, but they are special case so not included. 
For example all the `whatever/index.html`, should rel=canonical to `whatever/`, and the `gallery.html` should rel=canonical to `gallery/`; but those would be drowned in this PR.

**Comment by Carreau** [comment]
Thanks, much appreciated.

**Pull request merged**
