### PR TITLE
TST: fix link try 2

### PR DESCRIPTION
**Pull request by jklymak**
OK, this time I did `ln -s _test_redirect/index.html _junk.html` which is what I meant to do...

### CODE REVIEW

**Comment by tacaswell** [comment]
oh, sorry, I merged #33 which seems to have broken this...

**Comment by jklymak** [comment]
Hah, don't you be sorry!  I'm the one screwing up!

**Comment by jklymak** [comment]
OK, should be fixed

**Comment by jklymak** [comment]
@tacaswell OK to try a merge of this?

**Comment by jklymak** [comment]
OK, this doesn't work.  the redirect is indeed transparent.  Too bad!

**Pull request closed without merging**
